### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by MJDa** [orlandi/hamamatsuOrcaTools#1]
Hi,
I have been looking for a way to open automatically DCIMG files and save them to tiff files, and it looks like you code could be able to do that. Unfortunately, it does not work on my computer : it does open a window to ask me wich file I want to open, but then I get an error (see below) and a window opens with DCIMG metadata : 
bytes_per_img 2
ysize 100
xsize 32768
bytes_per_row  65537
binning 0
filesize 52437798
xsize_req 0
footer_loc 2251799813686384
bitdepth 0
nframes 0

Error:

Traceback (most recent call last):
  File "Plugins/DCIMG_opener.py", line 203, in <module>
    main()
  File "Plugins/DCIMG_opener.py", line 95, in main
    FileInfoVirtualStack(finfo)
	at ij.io.FileOpener.open(FileOpener.java:153)

	at ij.io.FileOpener.openImage(FileOpener.java:51)

	at ij.plugin.FileInfoVirtualStack.open(FileInfoVirtualStack.java:105)

	at ij.plugin.FileInfoVirtualStack.<init>(FileInfoVirtualStack.java:23)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)

	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:210)

java.lang.NullPointerException: java.lang.NullPointerException

Do you have an idea what is causing the issue ?
Thanks

**Comment by orlandi** [comment]
Hi,
Looks like there's an issue while reading the metadata (since it's detecting 0 frames).
This script is prepared to read .dcimg files recorded as an hcimage stream for an orca camera. If it's a different kind of .dcimg it might not work.
If it's the stream, I can probably help, but it's going to be very hard without access to the file. If you have a record with only a few frames I could take a look.
Also, there's a hamamatsu plugin for imagej that in theory can read dcimg files using their API (in windows). However, I found it extremely buggy and right now I cannot even find the link. If you are still interested let me know and I will look in the lab where we have it installed
